# ---------------配置节点hosts文件-----------------
- import_tasks: hostname.yml

# ---------------配置节点chrony服务----------------
- import_tasks: chrony.yml

# ---------------关闭节点无关服务------------------
- import_tasks: disable_services.yml

# --------------修补系统运行环境---------------------
- import_tasks: fix_system.yml

# --------------加载IPVS内核模块---------------------
- include_tasks: enable_ipvs.yml
  when: PROXY_MODE =="ipvs"

# -----------准备Kubernetes运行环境----------------
- name: 准备目标文件夹
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ tls_dir }}"
  - /root/.kube
 
- name: 分发证书工具CFSSL
  copy: src={{ base_dir }}/pkgs/cfssl/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: 修改环境变量$PATH
  shell: echo "export PATH={{ bin_dir }}:$PATH" >> $HOME/.bashrc && source $HOME/.bashrc
  ignore_errors: true
